language: node_js
node_js:
  - "6"
script:
  - npm run lint
  - npm run test
  - npm run build

branches:
  only:
    - master
    - develop

# Send coverage data to Coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
